name: Dispatch submodule update
on:
  workflow_call:
    inputs:
      sha:
        description: "Value of github.sha"
        required: true
        type: string
      repository:
        description: "Value of github.repository"
        required: true
        type: string
    secrets:
      UPDATE_SUBMODULE_PAT:
        description: "PAT to use for dispatching update"
        required: true
jobs:
  dispatch-submodule-update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ["krishnans2006/classes"]
    steps:
      - name: Push to repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.UPDATE_SUBMODULE_PAT }}
          repository: ${{ matrix.repo }}
          event-type: update
          client-payload: |-
            {
              "sha": "${{ inputs.sha }}",
              "repository": "${{ inputs.repository }}"
            }
