name: Do submodule update
on:
  workflow_call:
    inputs:
      sha:
        description: "Value of github.sha"
        required: true
        type: string
      repository:
        description: "Value of github.repository"
        required: true
        type: string
    secrets:
      DO_SUBMODULE_UPDATE_PAT:
        description: "PAT with write access to repo"
        required: true
jobs:
  do-submodule-update:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DO_SUBMODULE_UPDATE_PAT }}
      - name: Determine submodule path
        run: echo "SUBMODULE_PATH=`git config --file .gitmodules --get-regexp '\.url$' | sed -nr 's|^submodule\.(.*)\.url .*${{ inputs.repository }}$|\1|p'`" >> $GITHUB_ENV
      - name: Determine commit SHA representation
        run: echo "SHORT_SHA=`echo ${{ inputs.sha }} | cut -c1-7`" >> $GITHUB_ENV
      - name: Determine commit message
        run: echo "COMMIT_MSG=Update ${{ inputs.repository }} @ ${SHORT_SHA}" >> $GITHUB_ENV
      - name: Update submodule
        run: git update-index --cacheinfo "160000,${{ inputs.sha }},${SUBMODULE_PATH}"
      - name: Commit and push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
          git commit -am "${COMMIT_MSG}"
          git push
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
